# Generated by Django 2.0.6 on 2018-06-29 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentreport', '0002_studentsdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsdata',
            name='date_registered',
            field=models.DateField(default=datetime.date(2018, 6, 29)),
        ),
    ]
