# Generated by Django 2.0.6 on 2018-06-29 20:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studentreport', '0003_auto_20180629_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsdata',
            name='date_registered',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
